global com.kantox.beverages.domain.entities.Product productProcessed;

dialect "mvel"

rule "Green Tea discount"
    when Product(name == "Green Tea" && quantity%2 == 0)
    then
        System.out.println("==========Adding Green Tea discount=============");
        productProcessed.setDiscount((productProcessed.getQuantity() * productProcessed.price) / 2)
end

rule "Strawberry discount"
    when Product(name == "Strawberries" && quantity >= 3)
    then
        System.out.println("==========Adding strawberries discount=============");
        productProcessed.setDiscount(productProcessed.getQuantity() * 0.50)
end

rule "Coffee discount"
    when Product(name == "Coffee" && quantity >= 3)
    then
        System.out.println("==========Adding coffees discount=============");
        productProcessed.setDiscount(productProcessed.getPrice() * productProcessed.getQuantity()  - (productProcessed.getQuantity() * productProcessed.getPrice) / 3.0)
end